var hackathon = '<article><h1>Make it happen!</h1><p>TBD is all about what is To Be Done. <br>TBD’s hackathon is about making it happen - build an app, a product, a company over a weekend. <br>Here is how is works: show up Friday afternoon and pitch your startup idea to the group or hear from industry players what they’d like to see hackers produce for them. <br>Break into teams and code like hell for two days. <br>Build a prototype. <br>Demo your project on Sunday night. <br>Your team may win first prize. <br>Or even find a first customer. <br>Come get plugged in to the hottest startup event in Malmö!</p></article>';
var crew = '<article><h1>Crew</h1><ul><li>Marie Neubauer</li><li>Fredrik Carlsson</li><li>Jamal Reimer</li><li>Peter Neubauer</li><li>Claus Dahl</li><li>Erik Starck</li><li>Stefan Mossberg</li></ul></article>';


var manifesto = '<article><h1>TBD Manifesto</h1><p>Companies and organizations face an ever-advancing set of business challenges, many of which are addressable by technology. Wether it be the Human Genome Project or your local product faults database, there is a wealth of open and proprietary data sources, technologies and efforts that constitute an increasingly important asset for anyone that can harness it with meaningful visualization, analytics and connections to other data. However, many businesses do not have the means or bandwidth to access the knowledge and talent needed to make this happen. But they have a good view of the value of these solutions.</p><p>Innovators are coding in coffee shops, tinkering in garages and experimenting in labs and on campuses. How do they know up front if their ideas will be of value to enterprises or society at large? Their efforts need early validation and guidance from potential customers on what the market really needs and who are willing to fund and implement new technologies that solve critical issues.</p><p>TBD aims to create local ecosystems that bring together industry with talented, entrepreneurial problem-solvers - developers, hackers, designers, thought leaders and academics - to tackle real world challenges in a creative and free environment. Through virtual and real time events, activities and collaborative platforms, TBD\’s goal is to bridge and facilitate spontaneous collaboration between individuals, businesses and organizations and access to potential customers willing to engage for innovators, developers and startups.</p></article>';
var program = '<article><h1>Program</h1><h2>Friday, 10. Feb 2012, 18.00 – 24.00</h2><ul><li>personal presentations (30 sec/person)</li><li>challenge presentation (10 min/challenge)</li>	<li>forming of teams</li><li>team work starts</li></ul><h2>Saturday, 11. Feb 2012, 08.00 – 24.00</h2><ul><li>light breakfast</li><li>team work continues</li><li>lunch</li><li>team work</li><li>dinner</li></ul><h2>Sunday, 11. Feb 2012, 08.00 – 21.00</h2><ul><li>Facilitators will be available to the teams during the day.</li><li>Same as Saturday.</li><li>demo 17.00 – 19.00</li><li>dinner at 19.00</li><li>awards at 20.00</li></ul></article>';
var register = '<article><h1>Register</h1><p>You can register for the event as a participant or a sponsor. If you are participating (developer, designer, etc) you pay SEK 100 and sponsors can make a donation. The money goes to a Grand Prize, which will be given out on Sunday evening.</p><a href="http://t-b-d.eventbrite.com/">Registration</a></article>';
var sponsors = '<article><h1>Sponsors with bragging rights</h1><ul class="table"><li class="row"><a class="cell pr40" href="http://menmo.se/"><b>Menmo</b></a><p class="cell">Sponsoring the event location, Djäkne.</p></li><li class="row"><a class="cell pr40" href="http://mediaevolution.se/"><b>Media Evolution</b></a></li></ul></article>';
var help = '<article><ol class="table"><li class="row"><a class="hackathon c cell pr40" href="/hackathon/">hackathon</a><p class="cell">get details for the event</p></li><li class="row"><a class="program c cell pr40" href="/program/">program</a><p class="cell">get the schedule of the event</p></li><li class="row"><a class="register c cell pr40" href="/register/">register</a><p class="cell">get registration information and sign up</p></li><li class="row"><a class="sponsors c cell pr40" href="/sponsors/">sponsors</a><p class="cell">get a list of sponsors who made the event possible</p></li><li class="row"><a class="crew c cell pr40" href="/crew/">crew</a><p class="cell">get a list of event hosts and facilitators</p></li><li class="row"><a class="help c cell pr40" href="/help/">help</a><p class="cell">get list of commands</p></li></ol></article>';
var contact = '';
